-- Clear and reseed with real Snowmentum activities + links
delete from activities;

insert into activities (name, category, url, sort_order, active) values
('ADHD Storytelling','Storytelling','https://www.snowmentum.org/adhdstorytelling',1,true),
('Apocalypse MASH','Games','https://www.snowmentum.org/new-page-86',2,true),
('ASMR DIY','Creative','https://www.snowmentum.org/asmr-guy',3,true),
('Birthday Magic','Social','https://www.snowmentum.org/birthday-and-name-book',4,true),
('Blackout Poetry','Creative','https://www.snowmentum.org/blackout-poetry',5,true),
('Blind Trust Walk','Physical','https://www.snowmentum.org/build-a-tent',6,true),
('Breakup Central','Deep','https://www.snowmentum.org/breakup-central',7,true),
('Build a Frankensnowcrow','Creative','https://www.snowmentum.org/build-a-frankensnowcrow',8,true),
('Build a Snowballer','Creative','https://www.snowmentum.org/build-a-snowballer',9,true),
('Build a Tent','Physical','https://www.snowmentum.org/blind-trust-walk',10,true),
('Cars!','Physical','https://www.snowmentum.org/car-walk',11,true),
('Chalk Challenge','Creative','https://www.snowmentum.org/chalk-challenge',12,true),
('Combination Man','Creative','https://www.snowmentum.org/combination-snowmonster',13,true),
('Compliments','Deep','https://www.snowmentum.org/compliments',14,true),
('Craps','Games','https://www.snowmentum.org/craps',15,true),
('Create a Band','Music','https://www.snowmentum.org/create-a-band',16,true),
('Create a Single','Music','https://www.snowmentum.org/create-a-single',17,true),
('Create an Ad','Creative','https://www.snowmentum.org/create-an-ad',18,true),
('Create Your Own Sport','Physical','https://www.snowmentum.org/create-your-own-sport',19,true),
('Daily Routines','Storytelling','https://www.snowmentum.org/daily-routines',20,true),
('Dance Horse Darts','Games','https://www.snowmentum.org/dance-horse-darsk',21,true),
('Dance Horse','Physical','https://www.snowmentum.org/dance-horse',22,true),
('Dear Former Self','Deep','https://www.snowmentum.org/dear-former-self',23,true),
('Dear Future Self','Deep','https://www.snowmentum.org/dear-future-self',24,true),
('Death','Deep','https://www.snowmentum.org/death',25,true),
('Don''t Drop the Egg Baby','Physical','https://www.snowmentum.org/dont-drop-the-egg-baby',26,true),
('Dr. Seuss','Creative','https://www.snowmentum.org/dr-suess',27,true),
('Draw on Gallery','Creative','https://www.snowmentum.org/drawing',28,true),
('Find the Red Book','Games','https://www.snowmentum.org/find-the-red-book',29,true),
('Folding Story','Storytelling','https://www.snowmentum.org/folding-story',30,true),
('Free Sample Tour','Social',null,31,true),
('Gamify Juke Box','Music','https://www.snowmentum.org/gamify-jukebox',32,true),
('Group Eulogy','Storytelling','https://www.snowmentum.org/group-eulogy',33,true),
('Haiku to Artist','Music','https://www.snowmentum.org/haiku-to-artist',34,true),
('Haiku','Creative','https://www.snowmentum.org/haiku',35,true),
('Hand Jive','Physical','https://www.snowmentum.org/hand-jive',36,true),
('Hanzel and Gretel','Storytelling','https://www.snowmentum.org/new-page-47',37,true),
('Hero''s Journey','Storytelling','https://www.snowmentum.org/heros-journney',38,true),
('Hide and Seek','Physical','https://www.snowmentum.org/hide-and-seek',39,true),
('Hottest/Coldest','Games','https://www.snowmentum.org/hottest-coldest',40,true),
('Ice Cream Flavor Contest','Social','https://www.snowmentum.org/ice-cream-flavor-contest',41,true),
('Jackie + Hunter','Social','https://www.snowmentum.org/listicales-1',42,true),
('Kids Book Reading','Creative',null,43,true),
('Listicles','Creative','https://www.snowmentum.org/listicales',44,true),
('MadLibs','Games','https://www.snowmentum.org/new-page-87',45,true),
('Make Signs','Creative','https://www.snowmentum.org/make-signs',46,true),
('MASH','Games','https://www.snowmentum.org/new-page-86',47,true),
('Mayoral Speeches','Social','https://www.snowmentum.org/mayoral-speeches',48,true),
('Meet Dog Owners','Social','https://www.snowmentum.org/meet-dog-owners',49,true),
('Merry Go Round Ping Pong','Physical','https://www.snowmentum.org/new-page-32',50,true),
('Military Speeches','Social','https://www.snowmentum.org/miliary speeches',51,true),
('Missed Connections','Deep','https://www.snowmentum.org/missed-connections',52,true),
('Newspaper Fashion Show','Creative','https://www.snowmentum.org/newspaper-fashion-show',53,true),
('One Sentence','Storytelling','https://www.snowmentum.org/one-sentence',54,true),
('Oscar Speeches','Social','https://www.snowmentum.org/oscar-speeches',55,true),
('Photo Prompting','Creative','https://www.snowmentum.org/photo-prompting',56,true),
('Pick Up Lines','Social','https://www.snowmentum.org/pickup-lines',57,true),
('Pig Latin','Games','https://www.snowmentum.org/pig-latin',58,true),
('Playlist for Partner','Music','https://www.snowmentum.org/playlist-for-partners',59,true),
('Poetry','Creative','https://www.snowmentum.org/poetry',60,true),
('Pool Questions','Deep','https://www.snowmentum.org/pool-questions',61,true),
('Rally Ping Pong','Physical','https://www.snowmentum.org/rally',62,true),
('Ride Along Cop','Storytelling','https://www.snowmentum.org/new-page-29',63,true),
('Rock Paper Scissors Lizard Spock','Games',null,64,true),
('Sidewalk Chalk','Creative','https://www.snowmentum.org/sidewalk-chalk',65,true),
('Silent Coffee','Deep','https://www.snowmentum.org/silent-coffee',66,true),
('Song Story','Music','https://www.snowmentum.org/song-story',67,true),
('Spaz Pool','Physical','https://www.snowmentum.org/spaz-pool',68,true),
('Telestrations','Games','https://www.snowmentum.org/telestrations',69,true),
('Two Truths and a Lie','Social','https://www.snowmentum.org/two-truths-and-a-lie',70,true),
('Would You Rather','Social','https://www.snowmentum.org/would-you-rather',71,true),
('Write Letter','Deep','https://www.snowmentum.org/write-letters',72,true),
('Year Challenge','Deep','https://www.snowmentum.org/guess-the-year',73,true),
('Pot Smuggler','Games','https://www.snowmentum.org/potsmuggler',74,true),
('Drum Circle','Music','https://www.snowmentum.org/drum-circle',75,true),
('Dolores Park Around Noon','Social','https://www.snowmentum.org/dolores-park-around-noon',76,true),
('Prosthetic Leg','Creative','https://www.snowmentum.org/prosthetic-leg',77,true),
('Coming to Your City Moment','Social','https://www.snowmentum.org/coming-to-your-city-moment',78,true),
('Actor Needed for an Emotional Role','Creative','https://www.snowmentum.org/actor-neeed-for-emotional-role',79,true),
('Grooming Circle','Social','https://www.snowmentum.org/grooming-circle',80,true),
('I Want to Chase Someone','Physical','https://www.snowmentum.org/i-want-to-chase-someone',81,true),
('Cinder Blocks','Physical','https://www.snowmentum.org/cinderblocks',82,true),
('Simple Check-In','Social','https://www.snowmentum.org/simplecheckin',83,true),
('2002 Ford Focus','Storytelling','https://www.snowmentum.org/2002-ford-focus',84,true);
