-- Add keyword to parties table
alter table parties add column if not exists keyword text;

-- Activities table
create table if not exists activities (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  category text not null default 'Social',
  description text,
  url text,
  sort_order integer default 0,
  active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Enable RLS
alter table activities enable row level security;
create policy "Service role full access" on activities for all using (true);
create policy "Public read active activities" on activities for select using (active = true);

-- Seed with the existing 84 activities
insert into activities (name, category, sort_order) values
('Two Truths and a Lie','Storytelling',1),
('Never Have I Ever','Social',2),
('Hot Takes','Deep',3),
('Desert Island','Deep',4),
('Unpopular Opinions','Deep',5),
('Speed Friending','Social',6),
('Story Spine','Storytelling',7),
('Confession Cam','Storytelling',8),
('Rose Bud Thorn','Deep',9),
('Life Timeline','Storytelling',10),
('Superlatives','Social',11),
('Most Likely To','Social',12),
('Table Topics','Deep',13),
('36 Questions','Deep',14),
('Yes And Improv','Creative',15),
('One Word Story','Creative',16),
('Character Swap','Creative',17),
('Emotional Charades','Creative',18),
('Accent Challenge','Creative',19),
('Freeze Tag Improv','Creative',20),
('Soundtrack of Your Life','Music',21),
('Name That Tune','Music',22),
('Lip Sync Battle','Music',23),
('Karaoke Roulette','Music',24),
('Music Decade Trivia','Music',25),
('Human Knot','Physical',26),
('Trust Fall','Physical',27),
('Group Juggle','Physical',28),
('Warp Speed','Physical',29),
('Minefield','Physical',30),
('Trivia','Games',31),
('Codenames','Games',32),
('Werewolf','Games',33),
('Mafia','Games',34),
('Wavelength','Games',35),
('Jackbox','Games',36),
('Fishbowl','Games',37),
('Spyfall','Games',38),
('Drawful','Games',39),
('Quiplash','Games',40),
('Photo Challenge','Creative',41),
('Vision Board','Creative',42),
('Collaborative Drawing','Creative',43),
('Haiku Battle','Creative',44),
('Freestyle Rap','Music',45),
('Beat Boxing Circle','Music',46),
('Song Association','Music',47),
('Playlist Swap','Music',48),
('Scavenger Hunt','Physical',49),
('Relay Race','Physical',50),
('Dance Battle','Physical',51),
('Freeze Dance','Physical',52),
('Compliment Circle','Deep',53),
('Gratitude Round','Deep',54),
('Burning Questions','Deep',55),
('Speed Dating Questions','Social',56),
('First Impression','Social',57),
('Spirit Animal','Social',58),
('Bucket List Share','Deep',59),
('Fear Inventory','Deep',60),
('Future Self Letter','Deep',61),
('Childhood Memory','Storytelling',62),
('Embarrassing Story','Storytelling',63),
('Hero Journey','Storytelling',64),
('Turning Point','Storytelling',65),
('The Day Everything Changed','Storytelling',66),
('Blind Contour Drawing','Creative',67),
('Exquisite Corpse','Creative',68),
('Tableau Vivant','Creative',69),
('Sound Effects Story','Creative',70),
('Musical Chairs','Games',71),
('Bingo','Games',72),
('Heads Up','Games',73),
('Pictionary','Games',74),
('Taboo','Games',75),
('Telephone','Games',76),
('Zip Zap Zop','Physical',77),
('Energy Ball','Physical',78),
('Samurai','Physical',79),
('Big Wind Blows','Physical',80),
('This or That','Social',81),
('Would You Rather','Social',82),
('Assumptions','Social',83),
('Hot Seat','Deep',84);
